### ISSUE TITLE
Error! TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Zachary24** [rvaidun/berealviewer#11]
"Error! TypeError: Failed to fetch"
After putting in phone number on both self hosted version and the webapp. Have tried multiple phone numbers and it still occurs.

**Comment by alikaptanoglu** [comment]
die

**Comment by rvaidun** [comment]
My self hosted version of the CORS anywhere server used up all its hours for this month. Need to host another CORS anywhere server
