### ISSUE TITLE
Can't reach the site

### ISSUE THREAD

**Issue by Lxvin1111** [rvaidun/berealviewer#117]
Can't reach the site from Germany why.

**Comment by rvaidun** [comment]
It's working at https://befake-623af.web.app/
IDK why but firebase or njal.la (my domain registrar) screwed up and firebase is not able to connect with the domain even though I changed nothing 
<img width="949" alt="image" src="https://github.com/rvaidun/befake/assets/19789246/7e4c99ff-3535-4d8f-b0fe-278f8b01b5a3">
<img width="716" alt="image" src="https://github.com/rvaidun/befake/assets/19789246/3c60e855-75c9-4ea7-9f35-5a7d858cb5a6">

**Comment by rvaidun** [comment]
<img width="1288" alt="image" src="https://github.com/rvaidun/befake/assets/19789246/6889bbc1-4db1-4216-8355-cb791100c9a7">
Very weird issue, i'll give it like a day and then i might switch DNS providers. njal has been pretty reliable up until now
