### ISSUE TITLE
how can i host it locally? i dont really know about coding

### ISSUE THREAD

**Issue by WeitHardo** [rvaidun/berealviewer#142]
i dont know what what a npm is or how to use it

**Comment by sgsyhggggd** [comment]
same here

**Comment by jannistss** [comment]
> 

google it. you can test/use your own/forked github projects there.

**Comment by james-alt69** [comment]
how do you did it?
could you tell me by step?

**Comment by jannistss** [comment]
You need to open the github on a computer and fork the project. then login into vercelapp with your github account. By clicking on the + you cab create a new project and import a git repository.

**Comment by james-alt69** [comment]
thanks I appreciate your help

**Comment by s-alad** [comment]
Anyone struggling with this, I've fixed my client as rvaiduns got taken down. It's not as feature verbose but it should be working at: https://toofake.vercel.app/
