### ISSUE TITLE
awesome

### ISSUE THREAD

**Issue by alikaptanoglu** [rvaidun/berealviewer#3]
please add target profile view

**Comment by rvaidun** [comment]
What do you mean by target profile view?

**Comment by alikaptanoglu** [comment]
> What do you mean by target profile view?

such as we know username , show a user page ,this is possible?

![9bd12072-8408-4c7c-bc2a-4e3662da7964](https://user-images.githubusercontent.com/12663252/180648100-291d0932-f0db-4bdf-9060-002db5ea1c21.jpg)
